- name: ensure distribution repo is cloned
  git:
    repo: "https://github.com/docker/distribution.git"
    dest: "/root/distribution"
    update: "no"

- name: ensure modified dockerfile is uploaded
  copy:
    src: "Dockerfile"
    dest: "/root/distribution/"

- name: check if dockerimage exists
  command: docker images
  register: docker_images
  changed_when: false

- name: build dockerimage
  command: "docker build --tag rpi-registry ."
  args:
    chdir: "/root/distribution/"
  when: not docker_images.stdout | search('rpi-registry')
