- name: ensure distribution repo is cloned
  git:
    repo: "https://github.com/docker/distribution.git"
    dest: "/root/"

- name: ensure modified dockerfile is uploaded
  copy:
    src: "Dockerfile"
    dest: "/root/distribution/"

- name: check if dockerimage exists
  command: docker images
  register: docker_images

- name: ensure dockerimage is built
  command: "docker build --tag rpi-registry ."
  args:
    chdir: "/root/distribution/"
  when: not docker_images | search('rpi-registry')
